CREATE DATABASE IF NOT EXISTS COMMERCE;
USE COMMERCE;
CREATE TABLE IF NOT EXISTS PRODUCTOS(ID INT AUTO_INCREMENT, NOMBRE VARCHAR(60), CATEGORIA VARCHAR(100), PRECIO FLOAT, DISPONIBLE TINYINT(1), PRIMARY KEY(ID));
INSERT INTO PRODUCTOS(NOMBRE, CATEGORIA, PRECIO, DISPONIBLE) VALUES ("Raqueta de tenis", "Deportes", 13.70, 1);